### ISSUE TITLE
Instructions on including GeoLite2-Country.mmdb db ?

### ISSUE THREAD

**Issue by dhowe** [debricked/dmarc-visualizer#12]
I can't seem to get this running in my instance after uncommenting the appropriate line in parsedmarc/Dockerfile, downloading the GeoLite2-Country.mmdb file and placing it beside parsedmarc.ini (I also tried the top level).

ERROR:

> WARNING:utils.py:296:GeoLite2-Country.mmdb is missing. Please follow the instructions at https://dev.maxmind.com/geoip/geoipupdate/ to get the latest version.

**Comment by shawnventi** [comment]
Did you rebuild your Docker images after adding the `GeoLite2-Country.mmdb`?

To do this you can launch Docker Compose as follows: `docker compose up --build`

**Comment by dhowe** [comment]
That did  it, thanks
