### ISSUE TITLE
Blog post

### ISSUE THREAD

**Issue by EStech-it** [debricked/dmarc-visualizer#15]
Hello, I started using this project recently and just noticed that the blog you link to for instructions is no longer available, 404 error.

**Comment by EStech-it** [comment]
Blog post is back!

**Comment by supaeasy** [comment]
Without wanting to sound harsh, since this is a fantastic project: the blog post itself is not what I would call a proper instruction. If you need any, I would recommend the step by step in my repo.

**Comment by EStech-it** [comment]
It is a great project, simple to set up and useful. Im new to github. I didnt see any step by step here but the blog was helpful. I easily installed docker and have this running. Im just looking to add the geomapping and email pull and wanted to check the blog for additional info if there was any. Thank you for your reply.
