### ISSUE TITLE
parsedmarc quitting early while elasticsearch is starting up.

### ISSUE THREAD

**Issue by Archetrix** [debricked/dmarc-visualizer#3]
I just wanted to point out a slight change in docker-compose.yml to have parsedmarc restart on failure. Since elasticsearch may take some while until it's up parsedmac can retry a few times.

[docker-compose.yml.zip](https://github.com/debricked/dmarc-visualizer/files/5124475/docker-compose.yml.zip)

**Comment by sweoggy** [comment]
Thanks for pointing this out, solved by #5
