### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name does not resolve (dmarc-visualizer_parsedmarc_1 exited with code 1)

### ISSUE THREAD

**Issue by AboodAth99** [debricked/dmarc-visualizer#49]
When I build the cluster ( docker compose up) it appears this error:
arsedmarc_1     | 
parsedmarc_1     | During handling of the above exception, another exception occurred:
parsedmarc_1     | 
parsedmarc_1     | Traceback (most recent call last):
parsedmarc_1     |   File "/usr/local/bin/parsedmarc", line 8, in <module>
parsedmarc_1     |     sys.exit(_main())
parsedmarc_1     |   File "/usr/local/lib/python3.9/site-packages/parsedmarc/cli.py", line 821, in _main
parsedmarc_1     |     elastic.migrate_indexes(aggregate_indexes=[es_aggregate_index],
parsedmarc_1     |   File "/usr/local/lib/python3.9/site-packages/parsedmarc/elastic.py", line 241, in migrate_indexes
parsedmarc_1     |     if not Index(aggregate_index_name).exists():
parsedmarc_1     |   File "/usr/local/lib/python3.9/site-packages/elasticsearch_dsl/index.py", line 414, in exists
parsedmarc_1     |     return self._get_connection(using).indices.exists(index=self._name, **kwargs)
parsedmarc_1     |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
parsedmarc_1     |     return func(*args, params=params, headers=headers, **kwargs)
parsedmarc_1     |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/indices.py", line 332, in exists
parsedmarc_1     |     return self.transport.perform_request(
parsedmarc_1     |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 413, in perform_request
parsedmarc_1     |     raise e
parsedmarc_1     |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 381, in perform_request
parsedmarc_1     |     status, headers_response, data = connection.perform_request(
parsedmarc_1     |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 266, in perform_request
parsedmarc_1     |     raise ConnectionError("N/A", str(e), e)
parsedmarc_1     | elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb07b9cb880>: Failed to establish a new connection: [Errno -2] Name does not resolve) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fb07b9cb880>: Failed to establish a new connection: [Errno -2] Name does not resolve)

And in the dashboard appears "Elasticsearch error: Bad Gateway"

![image](https://github.com/debricked/dmarc-visualizer/assets/149593952/c09a286c-cea4-4d20-941a-833855bb2d56)

**Comment by AboodAth99** [comment]
@zozs

**Comment by ctoepfl** [comment]
do you know any solution?
